# alembic/versions/1e8659d420fa_initial_schema_setup.py

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8659d420fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    # op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False) 
    # ^ Удален, так как PK уже индексирован
    
    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    # ^ Удален, так как PK уже индексирован
    
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    
    op.create_table('products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('price', sa.Numeric(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ^ Удален, так как PK уже индексирован
    
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    # op.drop_index(op.f('ix_products_id'), table_name='products') # Удален
    op.drop_table('products')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    # op.drop_index(op.f('ix_categories_id'), table_name='categories') # Удален
    op.drop_table('categories')
    # op.drop_index(op.f('ix_users_id'), table_name='users') # Удален
    op.drop_table('users')
    # ### end Alembic commands ###